#!/usr/bin/env python3
"""
Generate PC-Pet event voice assets (PCP-015).

Synthesizes four short notification clips and emits BOTH:
  1. .wav files under firmware/pc_tamagotchi/assets/   (for listening/reference)
  2. firmware/pc_tamagotchi/pet_assets.h               (C arrays the firmware plays)

Format: 8-bit UNSIGNED mono PCM -- matches M5.Speaker.playRaw(const uint8_t*,
len, sample_rate). Clips are short + low rate to keep the flash footprint small.

Deterministic (no randomness): re-running reproduces identical output.
Standard library only.

Run:  python3 tools/gen_voice_assets.py
"""

import math
import os
import struct
import wave

SR = 11025  # sample rate (Hz)

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ASSET_DIR = os.path.join(ROOT, "firmware", "pc_tamagotchi", "assets")
HEADER = os.path.join(ROOT, "firmware", "pc_tamagotchi", "pet_assets.h")


def tone(freq, ms, vol=0.6):
    """A single tone with short attack/decay so it doesn't click. Returns floats -1..1."""
    n = int(SR * ms / 1000)
    out = []
    atk = max(1, int(n * 0.08))
    dec = max(1, int(n * 0.20))
    for i in range(n):
        env = 1.0
        if i < atk:
            env = i / atk
        elif i > n - dec:
            env = max(0.0, (n - i) / dec)
        out.append(vol * env * math.sin(2 * math.pi * freq * i / SR))
    return out


def sweep(f0, f1, ms, vol=0.6):
    """A linear pitch glide (used for the overheat/online flourishes)."""
    n = int(SR * ms / 1000)
    out = []
    atk = max(1, int(n * 0.05))
    dec = max(1, int(n * 0.15))
    phase = 0.0
    for i in range(n):
        f = f0 + (f1 - f0) * (i / n)
        phase += 2 * math.pi * f / SR
        env = 1.0
        if i < atk:
            env = i / atk
        elif i > n - dec:
            env = max(0.0, (n - i) / dec)
        out.append(vol * env * math.sin(phase))
    return out


def silence(ms):
    return [0.0] * int(SR * ms / 1000)


# ---- the four clips -------------------------------------------------------
# Keep each well under ~0.6 s. Frequencies chosen to feel "boot/alarm/sad/up".
CLIPS = {
    # rising major arpeggio C5-E5-G5-C6 -> friendly boot chime
    "BOOT": tone(523, 90) + tone(659, 90) + tone(784, 90) + tone(1047, 160),
    # descending warble -> "overheating" warning
    "OVERHEAT": sweep(1600, 1100, 130) + silence(30) + sweep(1500, 1000, 180),
    # low slow descent -> "low power"
    "LOWPWR": tone(700, 150) + silence(30) + tone(500, 150) + silence(30) + tone(350, 240),
    # quick rising 4-note -> "back online"
    "ONLINE": tone(784, 70) + tone(988, 70) + tone(1175, 70) + tone(1568, 150),
}


def to_u8(samples):
    """Float -1..1 -> unsigned 8-bit (0..255), centered at 128."""
    out = bytearray()
    for s in samples:
        v = int(round(128 + 127 * max(-1.0, min(1.0, s))))
        out.append(max(0, min(255, v)))
    return bytes(out)


def write_wav(path, pcm_u8):
    with wave.open(path, "wb") as w:
        w.setnchannels(1)
        w.setsampwidth(1)      # 8-bit
        w.setframerate(SR)
        w.writeframes(pcm_u8)


def emit_header(assets):
    lines = []
    lines.append("// pet_assets.h -- GENERATED by tools/gen_voice_assets.py. Do not edit by hand.")
    lines.append("//")
    lines.append("// Event voice clips (PCP-015): 8-bit unsigned mono PCM for")
    lines.append("// M5.Speaker.playRaw(const uint8_t*, len, VOICE_SR). On ESP32 these const")
    lines.append("// arrays live in memory-mapped flash, so no PROGMEM is needed.")
    lines.append("#pragma once")
    lines.append("#include <Arduino.h>")
    lines.append("")
    lines.append(f"const uint32_t VOICE_SR = {SR};")
    lines.append("")
    for name, pcm in assets.items():
        lines.append(f"const uint8_t VOICE_{name}_PCM[] = {{")
        row = []
        body = []
        for i, b in enumerate(pcm):
            row.append(str(b))
            if len(row) == 20:
                body.append("  " + ",".join(row) + ",")
                row = []
        if row:
            body.append("  " + ",".join(row) + ",")
        lines.extend(body)
        lines.append("};")
        lines.append(f"const size_t VOICE_{name}_LEN = sizeof(VOICE_{name}_PCM);")
        lines.append("")
    return "\n".join(lines) + "\n"


def main():
    os.makedirs(ASSET_DIR, exist_ok=True)
    pcms = {}
    total = 0
    for name, samples in CLIPS.items():
        pcm = to_u8(samples)
        pcms[name] = pcm
        total += len(pcm)
        write_wav(os.path.join(ASSET_DIR, name.lower() + ".wav"), pcm)
        print(f"  {name:9} {len(pcm):6} samples  {len(samples)/SR*1000:5.0f} ms")
    open(HEADER, "w").write(emit_header(pcms))
    print(f"total PCM: {total} bytes ({total/1024:.1f} KB) across {len(pcms)} clips")
    print(f"wrote {HEADER}")
    print(f"wrote {len(pcms)} .wav files to {ASSET_DIR}")


if __name__ == "__main__":
    main()
